function [activate_sensor] = sensor_env_module_parameters_2()
%SENSOR_ENV_MODULE_PARAMETERS_2 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
activate_sensor = 0.000000000000;


end