function [r_com,...
v_flock,...
eta] = Vicsek1995_module_parameters()
%VICSEK1995_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
r_com = 1.000000000000;
v_flock = 0.100000000000;
eta = 0.000000000000;


end