function [c_local,...
c_global,...
fit_f] = PSO_module_parameters()
%PSO_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
c_local = 0.500000000000;
c_global = 0.500000000000;
fit_f = ['@', '(', 'x', ',', 'x', '_', 't', ')', 'v', 'e', 'c', 'n', 'o', 'r', 'm', '(', 'x', '-', 'x', '_', 't', ')'];


end