function [command_upper_s,control_mode_s] = swarm_module_generate_desire(swarm_algorithm_type, t, states, sample_time, sensor_data_s, map3d_struct, terrain, terrain_params)
%SWARM_MODULE_GENERATE_DESIRE Generate the desired position and velocity
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated%   point-mass: state = [x; y; z; vx; vy; vz; ax; ay; az]
%   quadcopter: state = [x; y; z; vx; vy; vz; ax; ay; az; yaw; roll; Pitch];
% control_mode:
% TAKEOFF_TYPE = 2;
% HOVER_TYPE = 3;
% LAND_TYPE = 4;
% POSITION_CONTROL_TYPE = 5;
% VELOCITY_CONTROL_TYPE = 6;
% VELOCITY_HORIZONTAL_CONTROL_TYPE = 7;
switch swarm_algorithm_type
	case 'PSO'
		[command_upper_s,control_mode_s] = PSO_module_generate_desire(t, states, sample_time, sensor_data_s, map3d_struct, terrain, terrain_params);
	otherwise
		command_upper_s = [];
		control_mode_s = [];
end

end