function states_out = map_module_periodic_boundary(states_in)
%MAP_MODULE_PERIODIC_BOUNDARY 
%   

[activate,...
activate_periodic_boundary,...
x_range,...
y_range,...
z_range,...
x_color,...
x_alpha,...
y_color,...
y_alpha,...
z_color,...
z_alpha] = map_module_parameters();


states_out = states_in;
states_out(1,:) = deal_with_out_of_range(states_in(1,:),x_range(1),x_range(2));
states_out(2,:) = deal_with_out_of_range(states_in(2,:),y_range(1),y_range(2));
states_out(3,:) = deal_with_out_of_range(states_in(3,:),z_range(1),z_range(2));

    function out = deal_with_out_of_range(in,v_min,v_max)
        out = in;
        dv = (v_max-v_min);
        temp1 = in < v_min;
        out(temp1) = out(temp1) + dv;
        temp1 = in > v_max;
        out(temp1) = out(temp1) - dv;
    end

end
