function out = map_module_periodic_boundary_activate()
%MAP_MODULE_PERIODIC_BOUNDARY_ACTIVATE 
%   

[activate,...
activate_periodic_boundary,...
x_range,...
y_range,...
z_range,...
x_color,...
x_alpha,...
y_color,...
y_alpha,...
z_color,...
z_alpha] = map_module_parameters();

out = activate_periodic_boundary>0;

end

