function [flag_plot_traj,...
    flag_follow,...
    flag_save_data,...
    flag_save_video,...
    dimension,...
    time_trajectory,...
    video_speed] =...
    visual_module_parameters_deal(parameters_plot)
%PLOT_MODEL_PARAMETERS_DEAL 

count = 1;
flag_plot_traj = parameters_plot(count); count = count + 1;
flag_follow         = parameters_plot(count); count = count + 1;
flag_save_data = parameters_plot(count); count = count + 1;
flag_save_video = parameters_plot(count); count = count + 1;
dimension   = parameters_plot(count); count = count + 1;
time_trajectory     = parameters_plot(count); count = count + 1;
video_speed         = parameters_plot(count); count = count + 1;

end

