function [speed_max,...
theta_max,...
T_p] = point_mass_rotation_module_parameters()
%POINT_MASS_ROTATION_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
speed_max = 3.000000000000;
theta_max = 0.700000000000;
T_p = 0.100000000000;


end