function [r_com] = user_swarm_module_parameters()
%USER_SWARM_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
r_com = 4.000000000000;


end