function [velocity_noise] = noise_module_parameters()
%NOISE_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
velocity_noise = 0.050000000000;


end