function [a_max,...
v_max,...
T_p,...
T_v] = point_mass_module_parameters()
%POINT_MASS_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
a_max = 2.000000000000;
v_max = 1.500000000000;
T_p = 1.000000000000;
T_v = 1.000000000000;


end