function [velocity_noise] = noise_module_parameters_3()
%NOISE_MODULE_PARAMETERS_3 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
velocity_noise = 0.000000000000;


end