function [] = motion_module_parameters_6()
%MOTION_MODULE_PARAMETERS_6 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated


end