function [png,...
position,...
scale] = terrain_module_parameters()
%TERRAIN_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
png = "canyon_snow_sub.png";
position = [-236.000000000000
-185.000000000000
122.840000000000];
scale = [1.000000000000
1.000000000000
0.010000000000];


end