function [resolution,...
r_sense_min,...
r_sense_max,...
phi_range,...
psi_range] = lidar_module_parameters()
%LIDAR_MODULE_PARAMETERS 
% Automatically generated by read_parameter_xml.m
% Every time read_parameter_xml.m is run, this function will be generated
resolution = 0.017501908934;
r_sense_min = 0.150000000000;
r_sense_max = 3.000000000000;
phi_range = [0.000000000000
0.000000000000];
psi_range = [-3.141592653590
3.141592653590];


end