function [alpha,...
    dim,...
    v_flock,...
    r_rep,...
    dro,...
    dra,...
    sigma,...
    num,...
    heights] = Couzin_module_parameters_deal(parameters_flocking)
%COUZIN_MODULE_PARAMETERS_DEAL Summary of this function goes here
%   Detailed explanation goes here
myCount = 1;

alpha    = parameters_flocking(myCount); myCount = myCount + 1;
dim    = parameters_flocking(myCount); myCount = myCount + 1;
v_flock    = parameters_flocking(myCount); myCount = myCount + 1;
r_rep    = parameters_flocking(myCount); myCount = myCount + 1;
dro    = parameters_flocking(myCount); myCount = myCount + 1;
dra    = parameters_flocking(myCount); myCount = myCount + 1;
sigma    = parameters_flocking(myCount); myCount = myCount + 1;
num    = parameters_flocking(myCount); myCount = myCount + 1;
heights  = parameters_flocking(myCount:myCount+num-1); myCount = myCount + num;
end

